version: '2'

services:
  dm-backend:
    ports:
      - "5000:5000"
  mqtt:
    ports:
      - "8083:8083"
  influxdb:
    ports:
      - "8086:8086"
  mongodb:
    ports:
      - "27017:27017"
    

  
